---
# file: roles/ansible/tasks/main.yml

# The items who start with lib and the python-dev are neccesary to can execute the task "intall ansible with pip"
- name: "Install Ansible dependencies"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - libffi6
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-setuptools

- name: "Install ansible with pip"
  command: "pip install ansible"
