---

- hosts: ci
  sudo: yes
  gather_facts: no
  roles:
    - common_os_setup
    - dependencies
    - python2_latest
    - java8
    - sonar
    - ansible
    - jenkins
    - maven
    - nexus
    - apache
